name: Build Raspberry Pi OS Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache APT Packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-cache
        restore-keys: |
          ${{ runner.os }}-apt-cache

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip \
                                dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
                                gpg pigz xxd arch-test

    - name: Cache Build Data
      uses: actions/cache@v3
      with:
        path: work/
        key: ${{ runner.os }}-pigen-work-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pigen-work

    - name: Create Config File
      run: |
        echo "IMG_NAME='digital-signage-os'" > config
        echo "RELEASE='bookworm'" >> config
        echo "ENABLE_SSH=1" >> config
        echo "LOCALE_DEFAULT='en_US.UTF-8'" >> config
        echo "TIMEZONE_DEFAULT='America/New_York'" >> config
        echo "Created config file: "
        cat config

    - name: Run Raspberry Pi OS Build
      run: |
        chmod +x build-docker.sh
        ./build-docker.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RaspberryPiOS
        path: deploy/