name: Build Raspberry Pi OS Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Raspberry Pi OS Image
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip \
                                dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
                                gpg pigz xxd arch-test
        ./build-docker.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RaspberryPiOS
        path: deploy/